//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage25.Models
{
    using System;
    using System.Collections.Generic;
    using Garage25.Models;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class Vehicle
    {
        public int Id { get; set; }
        
        public int MemberId { get; set; }
        public virtual Member Member { get; set; }

        public int VehicleTypeId { get; set; }
        public virtual VehicleType VehicleType { get; set; }

        [DisplayName("Registration Number")]
        public string RegNr { get; set; }
        [DisplayName("Colour")]
        public string Color { get; set; }
        public string Make { get; set; }
        [DisplayName("Model")]
        public string VName { get; set; }
        //public int WheelTally { get; set; }
        [DisplayName("Check-in Time")]
        public DateTime CheckInTime { get; set; }
        [DisplayName("Check-out Time")]
        public DateTime CheckOutTime { get; set; }
    }
}
